### Listar tarefas
GET https://localhost:7064/api/tasks
Accept: application/json

###

### Criar tarefa válida
POST https://localhost:7064/api/tasks
Content-Type: application/json

{
  "title": "Estudar validações",
  "description": "Validando CreateTaskDto com DataAnnotations",
  "priority": "medium"
}

###

### Criar tarefa inválida - título curto
POST https://localhost:7064/api/tasks
Content-Type: application/json

{
  "title": "ab",
  "description": "Esse teste deve retornar erro de validação",
  "priority": "medium"
}

### Buscar tarefa por ID existente
GET https://localhost:7064/api/tasks/6a20b709a81a4b0039bec30c
Accept: application/json

###

### Buscar tarefa por ID inexistente
GET https://localhost:7064/api/tasks/999
Accept: application/json

### Atualizar tarefa existente
PUT https://localhost:7064/api/tasks/6a20b709a81a4b0039bec30c
Content-Type: application/json

{
  "title": "2º Tarefa no MongoDB",
  "description": "Testando update real no banco",
  "priority": "high"
}

###

### Atualizar tarefa inexistente
PUT https://localhost:7064/api/tasks/999
Content-Type: application/json

{
  "title": "Tarefa inexistente",
  "description": "Esse teste deve retornar 404",
  "priority": "low"
}

### Concluir tarefa existente
PATCH https://localhost:7064/api/tasks/6a20b709a81a4b0039bec30c/complete
Accept: application/json

###

### Concluir tarefa inexistente
PATCH https://localhost:7064/api/tasks/999/complete
Accept: application/json

### Excluir tarefa existente
DELETE https://localhost:7064/api/tasks/6a20e799215f6b62fe5f6fc1

###

### Excluir tarefa inexistente
DELETE https://localhost:7064/api/tasks/999