### Listar tarefas
GET https://localhost:7064/api/tasks
Accept: application/json

###

### Criar tarefa
POST https://localhost:7064/api/tasks
Content-Type: application/json

{
  "title": "Estudar POST no ASP.NET Core",
  "description": "Criar a primeira tarefa pela API",
  "priority": "high"
}

### Buscar tarefa por ID existente
GET https://localhost:7064/api/tasks/6
Accept: application/json

###

### Buscar tarefa por ID inexistente
GET https://localhost:7064/api/tasks/999
Accept: application/json

### Atualizar tarefa existente
PUT https://localhost:7064/api/tasks/1
Content-Type: application/json

{
  "title": "Estudar PUT no ASP.NET Core",
  "description": "Atualizar uma tarefa existente usando UpdateTaskDto",
  "priority": "high"
}

###

### Atualizar tarefa inexistente
PUT https://localhost:7064/api/tasks/999
Content-Type: application/json

{
  "title": "Tarefa inexistente",
  "description": "Esse teste deve retornar 404",
  "priority": "low"
}

### Concluir tarefa existente
PATCH https://localhost:7064/api/tasks/2/complete
Accept: application/json

###

### Concluir tarefa inexistente
PATCH https://localhost:7064/api/tasks/999/complete
Accept: application/json

### Excluir tarefa existente
DELETE https://localhost:7064/api/tasks/1

###

### Excluir tarefa inexistente
DELETE https://localhost:7064/api/tasks/999